import '@/styles/globals.css'
import type {Metadata} from 'next'
import {inter} from "@/styles/fonts";

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({children}: { children: React.ReactNode }) {
    return <html lang="nl-BE">
    <body className={inter.className}>
    {children}
    </body>
    </html>
}
